import type { ReactNode } from 'react'
import { EditorialArrow } from '@/components/icons/EditorialArrow'
import { MobileHero } from './MobileHero'
import { MobileSection, MobileCTA } from './MobileFrame'
import { MobileGallery } from './MobileGallery'
import { MobileInsights } from './MobileInsights'
import { LEGAL_AREAS, type LegalArea } from '@/lib/legal'
import { BUSINESS_AREAS } from '@/lib/business'
import { getAllArticles, toMeta, type Article } from '@/lib/blog'
import { CONTACT, NUNZIA_CONTACT, STUDIO_CONTACT, ADDRESS, NAPLES_ADDRESS, whatsappHref, nunziaWhatsappHref } from '@/lib/site'

export function MobileDirectory({ business=false }: {business?:boolean}) {
 const areas=business?BUSINESS_AREAS:LEGAL_AREAS
 return <><MobileHero label={business?'Business Advisory':'Legal expertise'} image={business?'/images/business-hero.png':'/images/blog/diritto-amministrativo.png'} position="65% 35%" title={business?<>Oltre i confini.<br /><em>Dentro ogni opportunità.</em></>:<>Conoscere il diritto.<br /><em>Proteggere ciò che conta.</em></>}><p>{business?'Strategia legale, accesso ai mercati e operazioni internazionali.':'Competenze specialistiche per imprese, professionisti, cittadini e Pubbliche Amministrazioni.'}</p><a className="m-text-link" href="#mobile-areas">Esplora le aree <EditorialArrow direction="down" /></a></MobileHero><MobileSection id="mobile-areas"><p className="m-label">Aree di attività</p><h2>{business?'Una visione internazionale.':'Una tutela integrata.'}</h2><div className="m-directory">{areas.map((a,i)=><article key={a.slug}><a href={a.href}><img loading="lazy" src={a.image} alt={a.imageAlt} style={{objectPosition:i===2?'50% 55%':'50% 40%'}} /><p className="m-label">{a.number} — {a.category}</p><div className="m-title-arrow"><h3>{a.title}</h3><EditorialArrow direction="external" /></div><p>{a.description}</p></a></article>)}</div></MobileSection><MobileCTA /></>
}

export function MobileLegalDetail({area}:{area:LegalArea}) {
 return <><MobileHero image={area.image} position="50% 35%" title={area.title} label={area.category}><p>{area.description}</p><a className="m-text-link" href="#mobile-chapters">Ambiti di assistenza <EditorialArrow direction="down" /></a></MobileHero><MobileSection id="mobile-chapters"><p className="m-label">Professionista di riferimento</p><h2>{area.professional}</h2><div className="m-chapters">{area.sections.map((s,i)=><details key={s.title} open={i===0}><summary><span>{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><b aria-hidden>+</b></summary><div>{s.paragraphs.map((p,j)=><p key={j}>{p}</p>)}</div></details>)}</div></MobileSection><MobileCTA /><MobileSection><a className="m-text-link" href="/specializzazioni-legali/">Tutte le specializzazioni <EditorialArrow /></a></MobileSection></>
}

export function MobileBusinessDetail({area,children}:{area:typeof BUSINESS_AREAS[number];children:ReactNode}) {
 return <><MobileHero image={area.image} title={area.title} label={area.category} position="60% 38%"><p>{area.description}</p><a className="m-text-link" href="#mobile-business-content">Approfondisci <EditorialArrow direction="down" /></a></MobileHero><div id="mobile-business-content" className="m-business-content">{children}</div><MobileCTA /><MobileSection><a className="m-text-link" href="/sezione-business/">Tutte le aree Business <EditorialArrow /></a></MobileSection></>
}

export function MobileBlog(){return <><MobileHero label="Insights · Archivio legale" image="/images/blog/diritto-amministrativo.png" title={<>Conoscere oggi.<br /><em>Decidere meglio.</em></>}><p>Analisi, orientamenti e aggiornamenti per interpretare il diritto e le sue conseguenze concrete.</p></MobileHero><MobileSection><MobileInsights articles={getAllArticles().map(toMeta)} searchable /></MobileSection></>}

export function MobileArticle({article,children}:{article:Article;children:ReactNode}) {return <><MobileHero label={article.category} image={article.coverImage} title={article.title}><p className="m-byline">{article.author}<br />{article.dateLabel} · {article.readingTime} min</p></MobileHero><MobileSection><article className="m-prose">{article.excerpt&&<p className="m-standfirst">{article.excerpt}</p>}{children}</article><a className="m-text-link" href="/blog/">Torna al blog <EditorialArrow /></a></MobileSection></>}

export function MobileGalleryPage(){return <><MobileHero label="Dentro LF Business" image="/images/gallery/foto-08.webp" title={<>Luoghi, incontri,<br /><em>relazioni.</em></>}><p>Il lato visibile della nostra esperienza.</p></MobileHero><MobileSection><MobileGallery /></MobileSection><MobileCTA /></>}

export function MobileContact(){return <><MobileHero label="Un confronto riservato" image="/images/contact-hero-cinematic.png" position="65% 50%" title={<>Ogni soluzione<br />inizia<br /><em>dall’ascolto.</em></>}><p>Parliamo della tua esigenza.</p><a className="m-button" href={whatsappHref}>Scrivi allo Studio <EditorialArrow /></a></MobileHero><MobileSection><p className="m-label">Contatti diretti</p><h2>Il tuo prossimo<br /><em>interlocutore.</em></h2><div className="m-contact-person"><h3>Avv. Luigi Ferrara</h3><a className="m-text-link" href={whatsappHref}>WhatsApp <EditorialArrow direction="external" /></a><a href={CONTACT.phoneHref}>{CONTACT.phone}</a></div><div className="m-contact-person"><h3>Avv. Nunzia Robustelli</h3><a className="m-text-link" href={nunziaWhatsappHref}>WhatsApp <EditorialArrow direction="external" /></a><a href={NUNZIA_CONTACT.phoneHref}>{NUNZIA_CONTACT.phone}</a></div><div className="m-contact-person"><h3>Studio di Sarno</h3><a href={STUDIO_CONTACT.phoneHref}>{STUDIO_CONTACT.phone}</a><a href={`mailto:${CONTACT.email}`}>{CONTACT.email}</a></div></MobileSection><MobileSection dark><p className="m-label">Dove incontrarci</p>{[ADDRESS,NAPLES_ADDRESS].map(a=><div className="m-contact-person" key={a.city}><h3>{a.city}</h3><p>{a.street}<br />{a.zip} · {a.country}</p><a className="m-text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a.mapsQuery)}`} target="_blank" rel="noopener noreferrer">Indicazioni <EditorialArrow direction="external" /></a></div>)}</MobileSection></>}

export function MobileCurriculum(){return <><MobileHero label="Profilo professionale" image="/images/luigi-ferrara-ritratto.png" position="54% 26%" title={<>Avv. Luigi<br /><em>Ferrara.</em></>}><p>Diritto amministrativo, Magistrature Superiori e consulenza strategica alle imprese.</p><a className="m-button" href="/documents/curriculum-luigi-ferrara.pdf" download>Scarica il curriculum <EditorialArrow direction="down" /></a></MobileHero><MobileSection><p className="m-label">Curriculum vitae</p><h2>Percorso,<br /><em>competenze e incarichi.</em></h2><div className="m-area-list">{[['2003','Iscrizione all’Ordine degli Avvocati'],['2015','Patrocinante presso le Magistrature Superiori'],['24 ORE','Partner del network professionale']].map(([year,text])=><div className="m-cv-item" key={year}><strong>{year}</strong><p>{text}</p></div>)}</div><p>Consulta il documento completo con il percorso professionale, le competenze e gli incarichi.</p><a className="m-text-link" href="/documents/curriculum-luigi-ferrara.pdf" target="_blank" rel="noopener noreferrer">Apri il documento PDF <EditorialArrow direction="external" /></a></MobileSection><MobileCTA /></>}
